# Generated by Django 4.1.3 on 2022-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
