# Generated by Django 4.1.3 on 2022-12-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw7', '0004_alter_doctors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinations',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
