# Generated by Django 4.1.3 on 2022-12-28 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw7', '0005_alter_examinations_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
