# Generated by Django 4.1.3 on 2023-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw7', '0006_alter_doctors_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Diseases',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Examinations',
        ),
        migrations.DeleteModel(
            name='Wards',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_base64',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
