# Generated by Django 4.1.3 on 2023-01-10 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaderjson', '0002_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AwayTeamScore',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Group',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='HomeTeamScore',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
