# Generated by Django 4.1.3 on 2022-12-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw8_home', '0002_department_doctor_doctorsexamination_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(),
        ),
    ]
